name: release

on:
  push:
    tags:
      - v**
  
jobs:
  build:
    name: Build application
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: "☁️ checkout repository"
        uses: actions/checkout@v2

  release:
    environment:
      name: prod
      url: https://github.com/${{ github.repository }}/releases/tag/${{ steps.semantic-release.outputs.release-tag }}
    name: Semantic Release
    needs: 
      - build

    